[PATCH] TMS380TR must select FW_LOADER
I got the following compile error with CONFIG_FW_LOADER=n:

<--  snip  -->

...
  LD      .tmp_vmlinux1
drivers/built-in.o(.text+0x297944): In function <BACKTICK>tms380tr_reset_adapter':
: undefined reference to <BACKTICK>request_firmware'
drivers/built-in.o(.text+0x297aaf): In function <BACKTICK>tms380tr_reset_adapter':
: undefined reference to <BACKTICK>release_firmware'
drivers/built-in.o(.text+0x297af9): In function <BACKTICK>tms380tr_reset_adapter':
: undefined reference to <BACKTICK>release_firmware'
make: *** [.tmp_vmlinux1] Error 1

<--  snip  -->

CONFIG_TMS380TR must select FW_LOADER (and therefore depend on HOTPLUG).

Signed-off-by: Adrian Bunk <bunk@fs.tum.de>