[PATCH] gcc-3.5: _exit fix
include/asm/unistd.h:397: warning: conflicting types for built-in function '_exit'

Just remove the dang thing - nobody uses _exit().

Except for the vmware stub, which breaks.  So I kindly exported do_exit() to
kernel modules, just for vmware...