[SCSI] Move cmd->{lun, target, channel} to cmd->device->{lun, id, channel}
This patch makes all of SCSI Core and LLDD use cmd->device->{lun, id, channel}, instead of the old cmd->{lun, target, channel}.

    * The new aic7xxx series driver has been partially converted. The problem is:
      drivers/scsi/aic7xxx/aic79xx_osm.c: In function <BACKTICK>ahd_linux_dv_fill_cmd':
      drivers/scsi/aic7xxx/aic79xx_osm.c:3304: structure has no member named <BACKTICK>host'
      drivers/scsi/aic7xxx/aic79xx_osm.c:3306: structure has no member named <BACKTICK>target'
      drivers/scsi/aic7xxx/aic79xx_osm.c:3307: structure has no member named <BACKTICK>lun'
      drivers/scsi/aic7xxx/aic79xx_osm.c:3308: structure has no member named <BACKTICK>channel'

      and the same thing in:
      drivers/scsi/aic7xxx/aic7xxx_osm.c: In function <BACKTICK>ahc_linux_dv_fill_cmd':
      drivers/scsi/aic7xxx/aic7xxx_osm.c:3154: structure has no member named <BACKTICK>host'
      drivers/scsi/aic7xxx/aic7xxx_osm.c:3156: structure has no member named <BACKTICK>target'
      drivers/scsi/aic7xxx/aic7xxx_osm.c:3157: structure has no member named <BACKTICK>lun'
      drivers/scsi/aic7xxx/aic7xxx_osm.c:3158: structure has no member named <BACKTICK>channel'
* cpqfsTSinit.c has a 2 line problem quite similar to the aic7xxx above.