[PATCH] USB: fix usb/serial/console.c compile error
The following compile error seems to come from Linus' tree:

<--  snip  -->

...
  CC      drivers/usb/serial/bus.o
  CC      drivers/usb/serial/console.o
drivers/usb/serial/console.c: In function <BACKTICK>usb_console_write':
drivers/usb/serial/console.c:221: warning: passing arg 3 of pointer to function makes integer from pointer without a cast
drivers/usb/serial/console.c:221: error: too many arguments to function
drivers/usb/serial/console.c:223: warning: passing arg 3 of <BACKTICK>usb_serial_generic_write' makes integer from pointer without a cast
drivers/usb/serial/console.c:223: error: too many arguments to function <BACKTICK>usb_serial_generic_write'
make[3]: *** [drivers/usb/serial/console.o] Error 1

<--  snip  -->

This was caused by the changed "write" in usb_serial_device_type.

Signed-off-by: Adrian Bunk <bunk@stusta.de>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>