[PATCH] Fix for more than 256 CPUs
From: Paul Jackson <pj@sgi.com>

The patch is needed to build NR_CPUS > 256.

Without this fix, you get compile errors:
    include/linux/cpumask.h: In function <BACKTICK>next_online_cpu':
    include/linux/cpumask.h:56: structure has no member named <BACKTICK>val'