[PATCH] numaq mempolicy.c build fix
From: William Lee Irwin III <wli@holomorphy.com>

mm/mempolicy.c: In function <BACKTICK>verify_pages':
mm/mempolicy.c:246: warning: implicit declaration of function <BACKTICK>kmap_atomic'
mm/mempolicy.c:249: warning: implicit declaration of function <BACKTICK>kunmap_atomic'

pte_offset_map() invokes kmap_atomic() via macro, without including the
required header.

Signed-off-by: Andrew Morton <akpm@osdl.org>
Signed-off-by: Linus Torvalds <torvalds@osdl.org>