[PATCH] x86-64: kernel/sys.c build fix
On x86-64, the attached patch is required to fix

> kernel/sys.c: In function <BACKTICK>sys_setsid':
> kernel/sys.c:1078: error: <BACKTICK>tty_sem' undeclared (first use in this function)
> kernel/sys.c:1078: error: (Each undeclared identifier is reported only once
> kernel/sys.c:1078: error: for each function it appears in.)

kernel/sys.c needs the tty_sem declaration from linux/tty.h.