[PATCH] qla1280.c doesn't compile
On Wed, Jan 07, 2004 at 11:28:31PM -0800, Andrew Morton wrote:
>...
> Changes since 2.6.1-rc1-mm2:
>...
> -qla1280-update.patch
> +qla1280-update-2.patch
>
>  Updated qlogic patch
>...

I got the following compile error when trying to compile this driver
statically into a kernel with hotplug enabled:

<--  snip  -->

...
drivers/scsi/qla1280.c:4849: error: <BACKTICK>qla1280_remove_one' undeclared here
(not in a function)
drivers/scsi/qla1280.c:4849: error: initializer element is not constant
drivers/scsi/qla1280.c:4849: error: (near initialization for
<BACKTICK>qla1280_pci_driver.remove')
make[2]: *** [drivers/scsi/qla1280.o] Error 1

<--  snip  -->

Since I don't see a good reason why qla1280_remove_one is #ifdef'ed out
in the non-modular case the patch below fixes this problem by removing
two #ifdef's.