[PATCH] fix linker trouble with CONFIG_FB_RIVA_I2C=y and modular I2C
From: Adrian Bunk <bunk@fs.tum.de>

> This version causes linker trouble with
> CONFIG_I2C=m
> CONFIG_I2C_ALGOBIT=m
> CONFIG_FB_RIVA_I2C=y
>
>   CC      init/version.o
>   LD      init/built-in.o
>   LD      .tmp_vmlinux1
> drivers/built-in.o(.text+0xda101): In function <BACKTICK>riva_setup_i2c_bus':
> : undefined reference to <BACKTICK>i2c_bit_add_bus'
> drivers/built-in.o(.text+0xda218): In function <BACKTICK>riva_delete_i2c_busses':
> : undefined reference to <BACKTICK>i2c_bit_del_bus'
> drivers/built-in.o(.text+0xda237): In function <BACKTICK>riva_delete_i2c_busses':
> : undefined reference to <BACKTICK>i2c_bit_del_bus'
> drivers/built-in.o(.text+0xda2c9): In function <BACKTICK>riva_do_probe_i2c_edid':
> : undefined reference to <BACKTICK>i2c_transfer'
> make: *** [.tmp_vmlinux1] Error 1
>...

The problem is:
FB_RIVA=y
FB_RIVA_I2C=y
I2C=m
I2C_ALGOBIT=m

The patch below fixes this.

Besides this, it contains:
- help text by Antonino A. Daplas
- converted spaces to tabs
- it was forgotten that FB_RIVA_I2C requires I2C_ALGOBIT

Signed-off-by: Andrew Morton <akpm@osdl.org>
Signed-off-by: Linus Torvalds <torvalds@osdl.org>